name: Build and Publish Package

on:
  push:
    tags:
      - 'cs16-client@*'
      - 'hlsdk-portable@*'
      - 'xash3d-fwgs@*'
      - 'webxash3d-mserver@*'

jobs:
  buildAndPublish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Parse tag to get package and version
        id: parse_tag
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "Full tag: $TAG"
          PACKAGE=${TAG%@*}
          VERSION=${TAG#*@}
          echo "package=$PACKAGE" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Ensure dist folder and raw.js are writable
        run: |
          DIST_DIR=packages/${{ steps.parse_tag.outputs.package }}/dist
          RAW_JS="$DIST_DIR/raw.js"
          
          # Ensure directory exists
          mkdir -p "$DIST_DIR"
          
          # Fix permissions on dist directory
          chmod -R u+w "$DIST_DIR"
          
          # If raw.js exists, fix its permissions too
          if [ -f "$RAW_JS" ]; then
            chmod u+w "$RAW_JS"
          fi
          
          # Optional: log permission info
          echo "Permissions of $RAW_JS:"
          ls -l "$RAW_JS" || echo "$RAW_JS not found (yet)"

      - name: Build package
        run: cd packages/${{ steps.parse_tag.outputs.package }} && npm run build

      - name: Publish NPM package
        run: cd packages/${{ steps.parse_tag.outputs.package }} && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "${{ steps.parse_tag.outputs.package }} v${{ steps.parse_tag.outputs.version }}"
          body: |
            🔖 **Release for** `${{ steps.parse_tag.outputs.package }}`  
            📦 **Version:** `${{ steps.parse_tag.outputs.version }}`
            🚀 **NPM:** [https://www.npmjs.com/package/${{ steps.parse_tag.outputs.package }}](https://www.npmjs.com/package/${{ steps.parse_tag.outputs.package }}/v/${{ steps.parse_tag.outputs.version }})
            
            📄 [Changelog](https://github.com/${{ github.repository }}/blob/${{ github.ref_name }}/packages/${{ steps.parse_tag.outputs.package }}/CHANGELOG.md)